name: 🔄 Update Kodi Playlist

on:
  push:
    paths:
      - kodi.py  # 📜 Trigger on script update
  schedule:
    - cron: '*/15 * * * *'  # ⏰ Every 15 minutes
  workflow_dispatch:  # 🔘 Manual trigger option

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0  # 🧠 Full git history

      - name: 🐍 Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: ⚙️ Run Kodi Playlist Generator
        run: python3 kodi.py

      - name: 🔧 Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 💾 Commit & Push Changes Safely
        run: |
          # Stash all local changes including untracked files before pulling
          git stash push -u -m "ci stash before pull" || true

          # Pull latest changes and rebase to avoid overwriting newer commits
          git pull --rebase origin main || {
            echo "⚠️ Pull with rebase failed, aborting rebase and restoring stash"
            git rebase --abort || true
            git stash pop || true
            exit 1
          }

          # Apply stashed changes back
          git stash pop || true

          # Add updated playlist file
          git add MergedPlaylist_Kodi.m3u8

          # Commit if there are changes
          git commit -m "📡 Auto-update Kodi formatted playlist at $(date -u)" || echo "🟡 No changes to commit"

          # Random delay to reduce push collisions
          sleep $((RANDOM % 10 + 5))

          # Push safely with lease protection
          git push --force-with-lease origin main
