name: 🔄 Auto Update Merged IPTV Playlist

on:
  schedule:
    - cron: '*/10 * * * *'  # ⏰ Every 10 minutes
  workflow_dispatch:        # 🔘 Manual trigger

concurrency:
  group: "iptv-playlist-update"
  cancel-in-progress: true

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 🕒 Print runner UTC time
        run: date -u

      - name: 📥 Checkout repo (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install dependencies
        run: pip install requests

      - name: 🧠 Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: ▶️ Run playlist generator
        run: |
          echo "# Last update: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" > MergedPlaylist.m3u8
          python iptv.py

      - name: 💾 Commit and push update safely
        run: |
          git add MergedPlaylist.m3u8
          git commit -m "📝 Update at $(date -u +"%Y-%m-%d %H:%M:%S UTC")" || echo "Nothing to commit."

          # 🔃 Pull latest changes with rebase to avoid stale push errors
          git pull --rebase origin main

          # ⏳ Random delay to reduce push collisions
          sleep $((RANDOM % 10 + 5))

          # 🚀 Push safely using force-with-lease
          git push --force-with-lease origin main
