name: 🚀 Update StreamEast Playlist 📺

on:
  schedule:
    - cron: '0 * * * *'  # ⏰ Run every hour on the hour (UTC)
  workflow_dispatch:       # 🔘 Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Python dependencies & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright urllib3 aiohttp
          playwright install firefox
          playwright install-deps

      - name: 🎯 Run scraping script
        run: python stream.py

      - name: 💾 Commit & Push if Playlist Changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add StreamEast.m3u8

          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
            exit 0
          fi

          git commit -m "🔁 Update playlist $(date -u)"

          # Rebase to avoid stale push
          git pull --rebase origin main

          # Push updates (no retry, will fail if stale)
          git push --force-with-lease origin main
