name: 🔄 Update Tims247 Playlist

on:
  schedule:
    - cron: '*/5 * * * *'  # ⏱ Auto update every 5 minutes
  workflow_dispatch:        # ✅ Manual trigger stays

permissions:
  contents: write           # ✅ Required to push changes from Actions

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0  # Full history for rebase

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install dependencies
        run: pip install requests

      - name: 🔄 Run Tims247 playlist update script
        run: python tim.py

      - name: 🕒 Force-inject timestamp (ensures commit even if only URL changes)
        run: |
          echo "# Updated at $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> Tims247.m3u8

      - name: 🧠 Set Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: 🔃 Pull latest changes and rebase
        run: git pull --rebase origin main || true

      - name: 💾 Commit and push updated playlist safely
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Tims247.m3u8
          git commit -m "Force update Tims247.m3u8 with timestamp at $(date -u)" || echo "No changes to commit"

          # Random sleep to reduce push collisions
          sleep $((RANDOM % 10 + 5))

          git push --force-with-lease origin main
